# Default values for ixia-c.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

controller:
    repository: ghcr.io/open-traffic-generator/ixia-c-controller
    pullPolicy: IfNotPresent
    tag: 0.0.1-3027
    name: ixia-c-controller-svc
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
serviceAccount:
  create: true
  annotations: {}
  name: ""
securityContext:
  privileged: true
  capabilities:
    add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RAWIO
      - NET_RAW
service:
  type: NodePort
  port: 8080
ingress:
  enabled: false
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
containerArgs:
  - "--http-port"
  - "8080"
  - "--accept-eula"
  - "--disable-app-usage-reporter"