apiVersion: v1
kind: Service
metadata:
  name: {{ include "te.fullname" . }}
  labels:
    {{- include "te.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: te
    {{ if .Values.bothTePe }}
    - port: 50071
      protocol: TCP
      name: pe
    {{ end }}
  selector:
    {{- include "te.selectorLabels" . | nindent 4 }}
