apiVersion: v1
kind: Service
metadata:
  name: {{ include "te.fullname" . }}
  labels:
    {{- include "te.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: te
    - port: 50071
      targetPort: 3500
      protocol: TCP
      name: pe
  selector:
    {{- include "te.selectorLabels" . | nindent 4 }}
