# Default values for te.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: ixia-c-traffic-engine-svc-2
egressDevice: veth2
te:
  repository: ixiacom/ixia-c-traffic-engine
  pullPolicy: IfNotPresent
  tag: 1.4.1.23
  # reserve a full CPU for athena traffic engine
  resources:
    limits:
      cpu: "1"
      memory: "500Mi"
pe:
  repository: "ixia-c-protocol-engine"
  pullPolicy: IfNotPresent
  tag: "1.00.0.152"
  resources:
    limits:
      memory: 2048Mi
egressInitJob:
  name: ixia-c-egress-init-job
  # bcm has iptools installed, so we use it to run the script
  repository: busybox:latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
serviceAccount:
  create: true
  annotations: {}
  name: ""
securityContext:
  privileged: true
  capabilities:
    add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RAWIO
      - NET_RAW
service:
  type: LoadBalancer
  port: 5556
ingress:
  enabled: false
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
optNoHugepages: "Yes"
optNoRx: "Yes" 
