name: Models CI/CD

# Trigger every time a push occurs
on:
  push:
  pull_request:
  workflow_dispatch:
    # paths:
    # - version.txt


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm

      # - name: Get version
      #   id: get_version
      #   run: |
      #     echo "::set-output name=version::v$(grep version api/info.yaml | sed -e 's/ //g')"
      # - name: Check tag for current version
      #   uses: mukunku/tag-exists-action@v1.0.0
      #   id: check_tag
      #   with:
      #     tag: ${{ steps.get_version.outputs.version }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create release and publish artifacts
      #   if: steps.check_tag.outputs.exists == 'false'
      #   uses: ncipollo/release-action@v1
      #   with:
      #     name: "Release ${{ steps.get_version.outputs.version }}"
      #     body: "View openapi.yaml spec at https://redocly.github.io/redoc/?url=https://github.com/open-traffic-generator/models/releases/download/${{ steps.get_version.outputs.version }}/openapi.yaml"
      #     artifacts: artifacts/openapi.yaml,artifacts/openapi.json,artifacts/otg.proto,artifacts/openapi.html
      #     tag: ${{ steps.get_version.outputs.version }}
      #     token: ${{ secrets.GITHUB_TOKEN }}